CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    CPF VAR,
    DATA_NASCIMENTO VARCHAR(10)
);

CREATE TABLE VACINA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME_VACINA VARCHAR(100)
);

CREATE TABLE CARTEIRA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INTEGER REFERENCES USUARIO(ID)
);

CREATE TABLE ITEM_CARTEIRA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_CARTEIRA INTEGER REFERENCES CARTEIRA(ID),
    ID_VACINA INTEGER REFERENCES VACINA(ID),
    DATA_VACINACAO TIMESTAMP
);

